/*©agpl*************************************************************************
*                                                                              *
* Friend Unifying Platform                                                     *
* ------------------------                                                     *
*                                                                              *
* Copyright 2014-2016 Friend Software Labs AS, all rights reserved.            *
* Hillevaagsveien 14, 4016 Stavanger, Norway                                   *
* Tel.: (+47) 40 72 96 56                                                      *
* Mail: info@friendos.com                                                      *
*                                                                              *
*****************************************************************************©*/

// Do not edit this file!
var server = {
	dev : false,
	mysql : {
		host : 'hello_database_host',
		port : 3206,
		user : 'hello_database_user',
		pass : 'hello_database_password',
		name : 'hello_database_name',
	},
	tls : {
		keyPath : 'path_to_key.pem',
		certPath : 'path_to_cert.pem',
		key : null,
		cert : null,
	},
	fc : {
		host : 'friendcore_host',
		port : 6502,
	},
	defaults : {
		// ACCOUNT
		account : {
			skipPass : true,
			settings : {
				popupChat : true,
				inAppMenu : false,
				msgAlert  : true,
			},
		},
		module : {
			//Presence
			presence : {
				displayName : 'Presence',
				host : 'presence_domain',
				port : 27960,
				settings : {
					
				},
			},
			// TREEROOT
			treeroot : {
				host : 'store.openfriendup.net',
				settings : {
					msgCrypto : false,
				},
			},
			// IRC
			irc : {
				host : 'irc.freenode.net',
				displayName : 'Freenode',
				login : '',
				password : '',
				settings : {
					join : [
						'#friendup',
					],
					connect : {
						tls : true,
						sasl : false,
						autoshow : true,
						autojoin : true,
					},
					user : 'FUP-irc',
					realName : '-',
				},
			},
		},
	},
};

var shared = {
	tls : true,
	force_no_tls : false,
	
	// port, listen
	// port is used by the client, set a number or fragment, 
	// depending on proxys and stuff.
	// listen is used by the server if defined.
	// example : server is listening on 3001 for chat sockets,
	// but is proxied by wss://example.com/hello/chat/
	// /hello/chat/ should be set as port in this config,
	// while 3001 should be set as listen
	// and is the actual port pointed to by the proxy:
	// port : '/hello/chat/',
	// listen : 3001,
	
	// if there is no proxy stuff, you can just use the port,
	// the server will use port if listen is not valid
	// port : 3001,
	// listen : null ( or simply undefined )
	
	http : {
		port : '/hello/', // not actually used, set in client config
		listen : 3000,
	},
	chat : {
		port : 3001,
		listen : null,
	},
	rtc : {
		signal : {
			port : 3002,
			listen : 3002,
		},
		iceServers : [
			{
				urls : [
					"stun:stun_url.com:3478",
				],
			},
			{
				urls : [
					"turn:turn_url.com:3478",
				],
				username : 'turn_username',
				credential : 'turn_password',
			},
		],
	},
	modules : {
		treeroot : {
			type : 'treeroot',
			name : 'Treeroot',
		},
		irc : {
			type : 'irc',
			name : 'IRC',
		},
	},
};

var conf = {
	shared : shared,
	server : server,
};

module.exports = conf;
